# Generated by Django 6.0.3 on 2026-03-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_alter_testsubmission_user_test_question_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=1, help_text='Marks for this question'),
        ),
        migrations.AddField(
            model_name='test',
            name='passing_marks',
            field=models.IntegerField(default=0, help_text='Minimum marks to pass (0 = no pass/fail)'),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='score',
            field=models.IntegerField(default=0, help_text='Auto-calculated score for MCQ questions'),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='time_taken_seconds',
            field=models.IntegerField(default=0, help_text='Time taken to complete the test in seconds'),
        ),
    ]
